### ISSUE TITLE
entityChanged event does not fire for new items in collection

### ISSUE THREAD

**Issue by nicoschoenmaker** [hostnet/entity-tracker-component#17]
When I configure a `OneToMany` or `ManyToMany` relation with a `cascade={"persist"}`, and add an item to that collection, the entityChanged event is not fired. Causing for me that the [`setRevision()`](https://github.com/hostnet/entity-revision-component/blob/master/src/RevisionableInterface.php#L14) method is not called.

A workaround is to call `$em->persist($new_item_in_collection)`, that does work. But does not match the expected behaviour of `cascade={"persist"}`.

**Comment by iltar** [comment]
`cascade={"persist"}` in fact does work. The problem is that this only gets detected _after_ doctrine has calculated the change set. This has not been done during `preFlush` and is therefore not yet detected.

**Comment by nicoschoenmaker** [comment]
Fixed in #26.
